version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
  node-red:
    image: nodered/node-red:latest
    volumes:
      - ./node-red/data:/data
    ports:
      - "1880:1880"
    restart: unless-stopped
  influxdb:
    image: influxdb:1.8
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    ports:
      - "8086:8086"
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped